version: '2.1'
services:
    
    db:
      image: mysql:5.7
      restart: always
      container_name: banco-ubs-mysql
      environment:
        MYSQL_DATABASE: 'ubsdata'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
        MYSQL_ROOT_PASSWORD: '123'

      ports:
        - '3306:3306'
      expose:
        - '3306'
    
